In [5]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [6]:
Income = pd.read_csv('Income_by_County.csv', delimiter=',',index_col=None) 

Income.head(10)

,County Name,Label _Grouping,Total,"Total Less than $10,000","Total $10,000 to $14,999","Total 15,000 to $24,999","Total $25,000 to $34,999","Total $35,000 to $49,999","Total $50,000 to $74,999","Total $75,000 to $99,999","Total $100,000 to $149,999","Total $150,000 to $199,999","Total $200,000 or more",Median income (dollars),Mean income (dollars),PERCENT ALLOCATED,PERCENT ALLOCATED Household income in the past 12 months,PERCENT ALLOCATED Family income in the past 12 months,PERCENT ALLOCATED Nonfamily income in the past 12 months
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Autauga County, Alabama","Autauga County, Alabama",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Autauga County, Alabama",Households,"21,559",6.20%,4.60%,12.30%,8.50%,12.70%,17.00%,13.40%,16.40%,4.80%,4.20%,"57,982","75,614",NaN,32.50%,(X),(X)
3,"Autauga County, Alabama",Estimate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Autauga County, Alabama",Families,"15,103",5.20%,2.60%,8.10%,7.20%,11.90%,17.70%,16.00%,19.40%,6.30%,5.70%,"70,730","88,331",NaN,(X),30.10%,(X)
5,"Autauga County, Alabama",Estimate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"Autauga County, Alabama",Married-couple families,"11,281",2.30%,1.10%,5.00%,7.30%,8.60%,17.80%,17.40%,25.20%,8.30%,7.10%,"87,738",N,NaN,(X),(X),(X)
7,"Autauga County, Alabama",Estimate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"Autauga County, Alabama",Nonfamily households,"6,456",10.30%,9.70%,22.20%,12.30%,13.90%,15.30%,6.50%,8.00%,1.40%,0.40%,"30,041","43,328",NaN,(X),(X),36.10%
9,"Autauga County, Alabama",Estimate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# DROP NaN VALUES FROM DATA
Drop_NA = Income.dropna(subset=['Total'])

Drop_NA.head(10)

,County Name,Label _Grouping,Total,"Total Less than $10,000","Total $10,000 to $14,999","Total 15,000 to $24,999","Total $25,000 to $34,999","Total $35,000 to $49,999","Total $50,000 to $74,999","Total $75,000 to $99,999","Total $100,000 to $149,999","Total $150,000 to $199,999","Total $200,000 or more",Median income (dollars),Mean income (dollars),PERCENT ALLOCATED,PERCENT ALLOCATED Household income in the past 12 months,PERCENT ALLOCATED Family income in the past 12 months,PERCENT ALLOCATED Nonfamily income in the past 12 months
2,"Autauga County, Alabama",Households,"21,559",6.20%,4.60%,12.30%,8.50%,12.70%,17.00%,13.40%,16.40%,4.80%,4.20%,"57,982","75,614",NaN,32.50%,(X),(X)
4,"Autauga County, Alabama",Families,"15,103",5.20%,2.60%,8.10%,7.20%,11.90%,17.70%,16.00%,19.40%,6.30%,5.70%,"70,730","88,331",NaN,(X),30.10%,(X)
6,"Autauga County, Alabama",Married-couple families,"11,281",2.30%,1.10%,5.00%,7.30%,8.60%,17.80%,17.40%,25.20%,8.30%,7.10%,"87,738",N,NaN,(X),(X),(X)
8,"Autauga County, Alabama",Nonfamily households,"6,456",10.30%,9.70%,22.20%,12.30%,13.90%,15.30%,6.50%,8.00%,1.40%,0.40%,"30,041","43,328",NaN,(X),(X),36.10%
11,"Baldwin County, Alabama",Households,"84,047",5.20%,4.80%,7.70%,10.00%,14.00%,16.80%,13.70%,15.50%,5.80%,6.60%,"61,756","83,626",NaN,34.60%,(X),(X)
13,"Baldwin County, Alabama",Families,"56,092",2.10%,1.90%,4.60%,7.50%,12.50%,17.70%,16.10%,20.20%,8.20%,9.20%,"79,907","101,693",NaN,(X),37.20%,(X)
15,"Baldwin County, Alabama",Married-couple families,"46,277",1.00%,0.80%,3.10%,5.90%,11.40%,17.00%,17.90%,22.90%,9.10%,10.90%,"88,867","111,411",NaN,(X),(X),(X)
17,"Baldwin County, Alabama",Nonfamily households,"27,955",11.80%,10.50%,14.30%,15.90%,16.50%,15.60%,7.40%,5.60%,1.00%,1.40%,"32,861","45,788",NaN,(X),(X),28.40%
20,"Barbour County, Alabama",Households,"9,322",14.60%,7.60%,18.40%,9.40%,12.50%,16.30%,7.30%,9.10%,2.20%,2.60%,"34,990","51,557",NaN,43.90%,(X),(X)
22,"Barbour County, Alabama",Families,"6,083",11.10%,5.40%,12.20%,12.00%,12.20%,19.50%,10.20%,10.70%,3.30%,3.30%,"45,836","60,687",NaN,(X),47.40%,(X)

In [12]:
Cleaned_Census = Drop_NA

In [13]:
Cleaned_Census.to_csv('Cleaned_Income_Data.csv', index=False)