In [57]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [58]:
Occupation = pd.read_csv('Occupation_by_County.csv', delimiter=',',index_col=None) 

Occupation.head(10)

,County_Name,Civilian employed population 16 years and over,"Agriculture, forestry, fishing and hunting, and mining",Construction,Manufacturing,Wholesale trade,Retail trade,"Transportation and warehousing, and utilities",Information,"Finance and insurance, and real estate and rental and leasing","Professional, scientific, and management, and administrative and waste management services","Educational services, and health care and social assistance","Arts, entertainment, and recreation, and accommodation and food services","Other services, except public administration",Public administration,PERCENT ALLOCATED,Industry
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Autauga County, Alabama","24,580",206,"1,847","2,721",798,"2,624","1,391",270,"1,349","2,411","5,013","2,075","1,233","2,642",NaN,10.30%
3,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Estimate,39.00%,39.30%,31.80%,25.90%,5.30%,7.70%,16.80%,56.30%,38.50%,52.50%,74.90%,18.80%,28.20%,49.80%,NaN,(X)
5,"Management, business, science, and arts oc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Estimate,15.30%,36.90%,0.00%,2.50%,0.00%,0.70%,0.40%,6.70%,0.00%,16.00%,12.80%,71.60%,33.70%,24.50%,NaN,(X)
7,Service occupations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Estimate,21.60%,0.00%,3.60%,11.10%,53.10%,64.60%,20.30%,20.40%,55.20%,22.60%,8.90%,8.00%,14.70%,15.60%,NaN,(X)
9,Sales and office occupations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
# DROP NaN VALUES FROM DATA
Drop_NA = Occupation.dropna(subset=['Information'])

Drop_NA.head(10)

,County_Name,Civilian employed population 16 years and over,"Agriculture, forestry, fishing and hunting, and mining",Construction,Manufacturing,Wholesale trade,Retail trade,"Transportation and warehousing, and utilities",Information,"Finance and insurance, and real estate and rental and leasing","Professional, scientific, and management, and administrative and waste management services","Educational services, and health care and social assistance","Arts, entertainment, and recreation, and accommodation and food services","Other services, except public administration",Public administration,PERCENT ALLOCATED,Industry
2,"Autauga County, Alabama","24,580",206,"1,847","2,721",798,"2,624","1,391",270,"1,349","2,411","5,013","2,075","1,233","2,642",NaN,10.30%
4,Estimate,39.00%,39.30%,31.80%,25.90%,5.30%,7.70%,16.80%,56.30%,38.50%,52.50%,74.90%,18.80%,28.20%,49.80%,NaN,(X)
6,Estimate,15.30%,36.90%,0.00%,2.50%,0.00%,0.70%,0.40%,6.70%,0.00%,16.00%,12.80%,71.60%,33.70%,24.50%,NaN,(X)
8,Estimate,21.60%,0.00%,3.60%,11.10%,53.10%,64.60%,20.30%,20.40%,55.20%,22.60%,8.90%,8.00%,14.70%,15.60%,NaN,(X)
10,Estimate,8.70%,23.80%,57.40%,6.50%,9.00%,8.50%,4.20%,16.70%,4.90%,1.00%,0.30%,0.80%,15.60%,5.10%,NaN,(X)
12,Estimate,15.30%,0.00%,7.10%,54.00%,32.60%,18.40%,58.40%,0.00%,1.40%,7.90%,3.20%,0.70%,7.80%,5.00%,NaN,(X)
15,"Baldwin County, Alabama","98,768","1,776","7,922","9,608","2,700","13,434","5,085","1,090","7,504","10,573","19,056","9,793","4,970","5,257",NaN,12.50%
17,Estimate,36.80%,19.00%,23.80%,32.10%,15.70%,11.60%,16.90%,50.30%,35.80%,49.40%,75.10%,20.80%,24.20%,41.40%,NaN,(X)
19,Estimate,17.30%,26.90%,1.10%,0.50%,0.00%,4.60%,1.70%,6.40%,9.80%,25.50%,14.40%,62.60%,33.50%,32.10%,NaN,(X)
21,Estimate,23.70%,5.30%,10.10%,12.50%,59.60%,60.60%,18.80%,21.60%,50.40%,18.70%,8.80%,12.20%,13.60%,19.50%,NaN,(X)

In [60]:
# DROP ESTIMATE ROWS
Cleaned_Census = Drop_NA[Drop_NA['County_Name'].str.contains('Estimate')==False]

Cleaned_Census.head()

,County_Name,Civilian employed population 16 years and over,"Agriculture, forestry, fishing and hunting, and mining",Construction,Manufacturing,Wholesale trade,Retail trade,"Transportation and warehousing, and utilities",Information,"Finance and insurance, and real estate and rental and leasing","Professional, scientific, and management, and administrative and waste management services","Educational services, and health care and social assistance","Arts, entertainment, and recreation, and accommodation and food services","Other services, except public administration",Public administration,PERCENT ALLOCATED,Industry
2,"Autauga County, Alabama","24,580",206,"1,847","2,721",798,"2,624","1,391",270,"1,349","2,411","5,013","2,075","1,233","2,642",NaN,10.30%
15,"Baldwin County, Alabama","98,768","1,776","7,922","9,608","2,700","13,434","5,085","1,090","7,504","10,573","19,056","9,793","4,970","5,257",NaN,12.50%
28,"Barbour County, Alabama","8,707",500,523,"2,091",179,930,492,68,341,444,"1,619",571,329,620,NaN,11.50%
41,"Bibb County, Alabama","8,303",392,781,"1,211",260,898,516,119,416,584,"1,862",272,515,477,NaN,13.60%
54,"Blount County, Alabama","22,836",378,"2,094","3,968",949,"2,376","1,736",225,"1,367","1,708","4,853","1,122","1,201",859,NaN,17.00%

In [61]:
Cleaned_Census.to_csv('Cleaned_Occupation_Data.csv', index=False)