In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("..\\Cleaned_Data\\AllYears_Data_Binning.csv")

In [3]:
data.head()

,Unnamed: 0,County_Name,State_Name,Civilian employed population 16 years and over_2010,"Agriculture, forestry, fishing and hunting, and mining_2010",Construction_2010,Manufacturing_2010,Wholesale trade_2010,Retail trade_2010,"Transportation and warehousing, and utilities_2010",...,"Arts, entertainment, and recreation, and accommodation and food services_2019","Other services, except public administration_2019",Public administration_2019,Industry_2015,2019_Median_AQI,2015_Median_AQI,2010_Median_AQI,2019_Binning,2015_Binning,2010_Binning
0,0,Baldwin County,Alabama,"77,263","1,302","6,489","6,134","2,131","9,525","3,557",...,"9,347","3,268","5,688",14.40%,37,38,43,2,2,2
1,4,Houston County,Alabama,"45,470",790,"2,967","4,237","1,897","6,225","2,838",...,"4,966","2,045","1,961",9.20%,35,33,48,2,2,2
2,5,Jefferson County,Alabama,"289,454","1,761","17,682","27,091","8,859","34,024","14,727",...,"29,352","17,315","13,683",14.90%,53,48,59,3,2,3
3,7,Madison County,Alabama,"156,411",569,"9,917","18,415","2,697","15,082","4,612",...,"17,436","8,656","17,602",10.30%,44,38,44,2,2,2
4,8,Mobile County,Alabama,"170,552","2,025","10,788","21,036","5,355","22,541","9,296",...,"15,804","10,200","8,642",11.50%,43,40,40,2,2,2

In [4]:
# Remove ',' from String literals in DataFrame
data['Civilian employed population 16 years and over_2010'] = data['Civilian employed population 16 years and over_2010'].str.replace(',','')
data['Agriculture, forestry, fishing and hunting, and mining_2010'] = data['Agriculture, forestry, fishing and hunting, and mining_2010'].str.replace(',','')
data['Construction_2010'] = data['Construction_2010'].str.replace(',','')
data['Manufacturing_2010'] = data['Manufacturing_2010'].str.replace(',','')
data['Wholesale trade_2010'] = data['Wholesale trade_2010'].str.replace(',','')
data['Retail trade_2010'] = data['Retail trade_2010'].str.replace(',','')
data['Transportation and warehousing, and utilities_2010'] = data['Transportation and warehousing, and utilities_2010'].str.replace(',','')
data['Information_2010'] = data['Information_2010'].str.replace(',','')
data['Finance and insurance, and real estate and rental and leasing_2010'] = data['Finance and insurance, and real estate and rental and leasing_2010'].str.replace(',','')
data['Professional, scientific, and management, and administrative and waste management services_2010'] = data['Professional, scientific, and management, and administrative and waste management services_2010'].str.replace(',','')
data['Educational services, and health care and social assistance_2010'] = data['Educational services, and health care and social assistance_2010'].str.replace(',','')
data['Arts, entertainment, and recreation, and accommodation and food services_2010'] = data['Arts, entertainment, and recreation, and accommodation and food services_2010'].str.replace(',','')
data['Other services, except public administration_2010'] = data['Other services, except public administration_2010'].str.replace(',','')
data['Public administration_2010'] = data['Public administration_2010'].str.replace(',','')

data['Civilian employed population 16 years and over_2015'] = data['Civilian employed population 16 years and over_2015'].str.replace(',','')
data['Agriculture, forestry, fishing and hunting, and mining_2015'] = data['Agriculture, forestry, fishing and hunting, and mining_2015'].str.replace(',','')
data['Construction_2015'] = data['Construction_2015'].str.replace(',','')
data['Manufacturing_2015'] = data['Manufacturing_2015'].str.replace(',','')
data['Wholesale trade_2015'] = data['Wholesale trade_2015'].str.replace(',','')
data['Retail trade_2015'] = data['Retail trade_2015'].str.replace(',','')
data['Transportation and warehousing, and utilities_2015'] = data['Transportation and warehousing, and utilities_2015'].str.replace(',','')
data['Information_2015'] = data['Information_2015'].str.replace(',','')
data['Finance and insurance, and real estate and rental and leasing_2015'] = data['Finance and insurance, and real estate and rental and leasing_2015'].str.replace(',','')
data['Professional, scientific, and management, and administrative and waste management services_2015'] = data['Professional, scientific, and management, and administrative and waste management services_2015'].str.replace(',','')
data['Educational services, and health care and social assistance_2015'] = data['Educational services, and health care and social assistance_2015'].str.replace(',','')
data['Arts, entertainment, and recreation, and accommodation and food services_2015'] = data['Arts, entertainment, and recreation, and accommodation and food services_2015'].str.replace(',','')
data['Other services, except public administration_2015'] = data['Other services, except public administration_2015'].str.replace(',','')
data['Public administration_2015'] = data['Public administration_2015'].str.replace(',','')

data['Civilian employed population 16 years and over_2019'] = data['Civilian employed population 16 years and over_2019'].str.replace(',','')
data['Agriculture, forestry, fishing and hunting, and mining_2019'] = data['Agriculture, forestry, fishing and hunting, and mining_2019'].str.replace(',','')
data['Construction_2019'] = data['Construction_2019'].str.replace(',','')
data['Manufacturing_2019'] = data['Manufacturing_2019'].str.replace(',','')
data['Wholesale trade_2019'] = data['Wholesale trade_2019'].str.replace(',','')
data['Retail trade_2019'] = data['Retail trade_2019'].str.replace(',','')
data['Transportation and warehousing, and utilities_2019'] = data['Transportation and warehousing, and utilities_2019'].str.replace(',','')
data['Information_2019'] = data['Information_2019'].str.replace(',','')
data['Finance and insurance, and real estate and rental and leasing_2019'] = data['Finance and insurance, and real estate and rental and leasing_2019'].str.replace(',','')
data['Professional, scientific, and management, and administrative and waste management services_2019'] = data['Professional, scientific, and management, and administrative and waste management services_2019'].str.replace(',','')
data['Educational services, and health care and social assistance_2019'] = data['Educational services, and health care and social assistance_2019'].str.replace(',','')
data['Arts, entertainment, and recreation, and accommodation and food services_2019'] = data['Arts, entertainment, and recreation, and accommodation and food services_2019'].str.replace(',','')
data['Other services, except public administration_2019'] = data['Other services, except public administration_2019'].str.replace(',','')
data['Public administration_2019'] = data['Public administration_2019'].str.replace(',','')

In [5]:
# Remove industry_2010 column
del data['Industry_2010']
del data['Industry_2015']
del data['Industry_2019']
del data['County_Name']
del data['State_Name']

In [6]:
data.head()

,Unnamed: 0,Civilian employed population 16 years and over_2010,"Agriculture, forestry, fishing and hunting, and mining_2010",Construction_2010,Manufacturing_2010,Wholesale trade_2010,Retail trade_2010,"Transportation and warehousing, and utilities_2010",Information_2010,"Finance and insurance, and real estate and rental and leasing_2010",...,"Educational services, and health care and social assistance_2019","Arts, entertainment, and recreation, and accommodation and food services_2019","Other services, except public administration_2019",Public administration_2019,2019_Median_AQI,2015_Median_AQI,2010_Median_AQI,2019_Binning,2015_Binning,2010_Binning
0,0,77263,1302,6489,6134,2131,9525,3557,940,5893,...,21683,9347,3268,5688,37,38,43,2,2,2
1,4,45470,790,2967,4237,1897,6225,2838,670,1980,...,10124,4966,2045,1961,35,33,48,2,2,2
2,5,289454,1761,17682,27091,8859,34024,14727,8309,25021,...,78297,29352,17315,13683,53,48,59,3,2,3
3,7,156411,569,9917,18415,2697,15082,4612,4594,7674,...,36515,17436,8656,17602,44,38,44,2,2,2
4,8,170552,2025,10788,21036,5355,22541,9296,2413,8469,...,40716,15804,10200,8642,43,40,40,2,2,2

In [7]:
# Convert values in data_2010 to integer type for Regression
data_new = data.copy()
data_new = data_new.astype(int)

In [8]:
# Convert values in data_2010 to proportion of total employed
data_new['Agriculture, forestry, fishing and hunting, and mining_2010'] = (data_new['Agriculture, forestry, fishing and hunting, and mining_2010']/data_new['Civilian employed population 16 years and over_2010'])*100
data_new['Construction_2010'] = (data_new['Construction_2010']/data_new['Civilian employed population 16 years and over_2010'])*100
data_new['Manufacturing_2010'] = (data_new['Manufacturing_2010']/data_new['Civilian employed population 16 years and over_2010'])*100
data_new['Wholesale trade_2010'] = (data_new['Wholesale trade_2010']/data_new['Civilian employed population 16 years and over_2010'])*100
data_new['Retail trade_2010'] = (data_new['Retail trade_2010']/data_new['Civilian employed population 16 years and over_2010'])*100
data_new['Transportation and warehousing, and utilities_2010'] = (data_new['Transportation and warehousing, and utilities_2010']/data_new['Civilian employed population 16 years and over_2010'])*100
data_new['Information_2010'] = (data_new['Information_2010']/data_new['Civilian employed population 16 years and over_2010'])*100
data_new['Finance and insurance, and real estate and rental and leasing_2010'] = (data_new['Finance and insurance, and real estate and rental and leasing_2010']/data_new['Civilian employed population 16 years and over_2010'])*100
data_new['Professional, scientific, and management, and administrative and waste management services_2010'] = (data_new['Professional, scientific, and management, and administrative and waste management services_2010']/data_new['Civilian employed population 16 years and over_2010'])*100
data_new['Educational services, and health care and social assistance_2010'] = (data_new['Educational services, and health care and social assistance_2010']/data_new['Civilian employed population 16 years and over_2010'])*100
data_new['Arts, entertainment, and recreation, and accommodation and food services_2010'] = (data_new['Arts, entertainment, and recreation, and accommodation and food services_2010']/data_new['Civilian employed population 16 years and over_2010'])*100
data_new['Other services, except public administration_2010'] = (data_new['Other services, except public administration_2010']/data_new['Civilian employed population 16 years and over_2010'])*100
data_new['Public administration_2010'] = (data_new['Public administration_2010']/data_new['Civilian employed population 16 years and over_2010'])*100

# Convert values in data_2015 to proportion of total employed
data_new['Agriculture, forestry, fishing and hunting, and mining_2015'] = (data_new['Agriculture, forestry, fishing and hunting, and mining_2015']/data_new['Civilian employed population 16 years and over_2015'])*100
data_new['Construction_2015'] = (data_new['Construction_2015']/data_new['Civilian employed population 16 years and over_2015'])*100
data_new['Manufacturing_2015'] = (data_new['Manufacturing_2015']/data_new['Civilian employed population 16 years and over_2015'])*100
data_new['Wholesale trade_2015'] = (data_new['Wholesale trade_2015']/data_new['Civilian employed population 16 years and over_2015'])*100
data_new['Retail trade_2015'] = (data_new['Retail trade_2015']/data_new['Civilian employed population 16 years and over_2015'])*100
data_new['Transportation and warehousing, and utilities_2015'] = (data_new['Transportation and warehousing, and utilities_2015']/data_new['Civilian employed population 16 years and over_2015'])*100
data_new['Information_2015'] = (data_new['Information_2015']/data_new['Civilian employed population 16 years and over_2015'])*100
data_new['Finance and insurance, and real estate and rental and leasing_2015'] = (data_new['Finance and insurance, and real estate and rental and leasing_2015']/data_new['Civilian employed population 16 years and over_2015'])*100
data_new['Professional, scientific, and management, and administrative and waste management services_2015'] = (data_new['Professional, scientific, and management, and administrative and waste management services_2015']/data_new['Civilian employed population 16 years and over_2015'])*100
data_new['Educational services, and health care and social assistance_2015'] = (data_new['Educational services, and health care and social assistance_2015']/data_new['Civilian employed population 16 years and over_2015'])*100
data_new['Arts, entertainment, and recreation, and accommodation and food services_2015'] = (data_new['Arts, entertainment, and recreation, and accommodation and food services_2015']/data_new['Civilian employed population 16 years and over_2015'])*100
data_new['Other services, except public administration_2015'] = (data_new['Other services, except public administration_2015']/data_new['Civilian employed population 16 years and over_2015'])*100
data_new['Public administration_2015'] = (data_new['Public administration_2015']/data_new['Civilian employed population 16 years and over_2015'])*100

# Convert values in data_2019 to proportion of total employed
data_new['Agriculture, forestry, fishing and hunting, and mining_2019'] = (data_new['Agriculture, forestry, fishing and hunting, and mining_2019']/data_new['Civilian employed population 16 years and over_2019'])*100
data_new['Construction_2019'] = (data_new['Construction_2019']/data_new['Civilian employed population 16 years and over_2019'])*100
data_new['Manufacturing_2019'] = (data_new['Manufacturing_2019']/data_new['Civilian employed population 16 years and over_2019'])*100
data_new['Wholesale trade_2019'] = (data_new['Wholesale trade_2019']/data_new['Civilian employed population 16 years and over_2019'])*100
data_new['Retail trade_2019'] = (data_new['Retail trade_2019']/data_new['Civilian employed population 16 years and over_2019'])*100
data_new['Transportation and warehousing, and utilities_2019'] = (data_new['Transportation and warehousing, and utilities_2019']/data_new['Civilian employed population 16 years and over_2019'])*100
data_new['Information_2019'] = (data_new['Information_2019']/data_new['Civilian employed population 16 years and over_2019'])*100
data_new['Finance and insurance, and real estate and rental and leasing_2019'] = (data_new['Finance and insurance, and real estate and rental and leasing_2019']/data_new['Civilian employed population 16 years and over_2019'])*100
data_new['Professional, scientific, and management, and administrative and waste management services_2019'] = (data_new['Professional, scientific, and management, and administrative and waste management services_2019']/data_new['Civilian employed population 16 years and over_2019'])*100
data_new['Educational services, and health care and social assistance_2019'] = (data_new['Educational services, and health care and social assistance_2019']/data_new['Civilian employed population 16 years and over_2019'])*100
data_new['Arts, entertainment, and recreation, and accommodation and food services_2019'] = (data_new['Arts, entertainment, and recreation, and accommodation and food services_2019']/data_new['Civilian employed population 16 years and over_2019'])*100
data_new['Other services, except public administration_2019'] = (data_new['Other services, except public administration_2019']/data_new['Civilian employed population 16 years and over_2019'])*100
data_new['Public administration_2019'] = (data_new['Public administration_2019']/data_new['Civilian employed population 16 years and over_2019'])*100

In [9]:
x = data_new[['Agriculture, forestry, fishing and hunting, and mining_2010','Construction_2010','Manufacturing_2010','Wholesale trade_2010','Retail trade_2010', 'Transportation and warehousing, and utilities_2010','Information_2010','Finance and insurance, and real estate and rental and leasing_2010', 'Professional, scientific, and management, and administrative and waste management services_2010','Educational services, and health care and social assistance_2010','Arts, entertainment, and recreation, and accommodation and food services_2010','Other services, except public administration_2010','Public administration_2010']]
y = data_new['2010_Binning']

from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data = pd.DataFrame()
vif_data["feature"] = x.columns
vif_data["VIF"] = [variance_inflation_factor(x.values, i) for i in range(len(x.columns))]
print(vif_data)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=100)

from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train, y_train)

                                              feature        VIF
0   Agriculture, forestry, fishing and hunting, an...   1.785733
1                                   Construction_2010  19.059585
2                                  Manufacturing_2010   6.483578
3                                Wholesale trade_2010  13.618890
4                                   Retail trade_2010  49.975024
5   Transportation and warehousing, and utilities_...  11.675501
6                                    Information_2010  11.409443
7   Finance and insurance, and real estate and ren...  11.752594
8   Professional, scientific, and management, and ...  20.148029
9   Educational services, and health care and soci...  24.564686
10  Arts, entertainment, and recreation, and accom...  13.264993
11  Other services, except public administration_2010  30.438917
12                         Public administration_2010   5.445901

LinearRegression()

In [10]:
print("Intercept: ", mlr.intercept_)
print("Coefficients:")
list(zip(x, mlr.coef_))

Intercept:  2.663193312260181
Coefficients:

[('Agriculture, forestry, fishing and hunting, and mining_2010',
  0.007702675786106176),
 ('Construction_2010', -0.03012022540274907),
 ('Manufacturing_2010', -0.007626172939389912),
 ('Wholesale trade_2010', 0.019301090771221496),
 ('Retail trade_2010', -0.012489453196346426),
 ('Transportation and warehousing, and utilities_2010', -0.007563806539869541),
 ('Information_2010', 0.03780500211255122),
 ('Finance and insurance, and real estate and rental and leasing_2010',
  -0.015374143858463463),
 ('Professional, scientific, and management, and administrative and waste management services_2010',
  -0.01225542560169631),
 ('Educational services, and health care and social assistance_2010',
  -0.006751097185481043),
 ('Arts, entertainment, and recreation, and accommodation and food services_2010',
  0.003656715069566721),
 ('Other services, except public administration_2010', 0.03742505357731063),
 ('Public administration_2010', -0.013710212592760465)]

In [11]:
#Prediction of test set
y_pred_mlr= mlr.predict(x_test)

from sklearn import metrics
meanAbErr = metrics.mean_absolute_error(y_test, y_pred_mlr)
meanSqErr = metrics.mean_squared_error(y_test, y_pred_mlr)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(y_test, y_pred_mlr))
print('R squared: {:.2f}'.format(mlr.score(x_test,y_test)))
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

R squared: -0.02
Mean Absolute Error: 0.33331871890035686
Mean Square Error: 0.268036839149062
Root Mean Square Error: 0.5177227435114881

In [12]:
x = data_new[['Agriculture, forestry, fishing and hunting, and mining_2015','Construction_2015','Manufacturing_2015','Wholesale trade_2015','Retail trade_2015', 'Transportation and warehousing, and utilities_2015','Information_2015','Finance and insurance, and real estate and rental and leasing_2015', 'Professional, scientific, and management, and administrative and waste management services_2015','Educational services, and health care and social assistance_2015','Arts, entertainment, and recreation, and accommodation and food services_2015','Other services, except public administration_2015','Public administration_2015']]
y = data_new['2015_Binning']

from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data = pd.DataFrame()
vif_data["feature"] = x.columns
vif_data["VIF"] = [variance_inflation_factor(x.values, i) for i in range(len(x.columns))]
print(vif_data)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=100)

from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train, y_train)

                                              feature        VIF
0   Agriculture, forestry, fishing and hunting, an...   1.756315
1                                   Construction_2015  17.023297
2                                  Manufacturing_2015   5.535015
3                                Wholesale trade_2015  13.756516
4                                   Retail trade_2015  48.026023
5   Transportation and warehousing, and utilities_...  10.806648
6                                    Information_2015  11.762493
7   Finance and insurance, and real estate and ren...  12.599692
8   Professional, scientific, and management, and ...  23.589361
9   Educational services, and health care and soci...  23.514338
10  Arts, entertainment, and recreation, and accom...  15.521685
11  Other services, except public administration_2015  32.156676
12                         Public administration_2015   5.394275

LinearRegression()

In [13]:
print("Intercept: ", mlr.intercept_)
print("Coefficients:")
list(zip(x, mlr.coef_))

Intercept:  45190926255741.336
Coefficients:

[('Agriculture, forestry, fishing and hunting, and mining_2015',
  -451909262557.3417),
 ('Construction_2015', -451909262557.4186),
 ('Manufacturing_2015', -451909262557.395),
 ('Wholesale trade_2015', -451909262557.3683),
 ('Retail trade_2015', -451909262557.4019),
 ('Transportation and warehousing, and utilities_2015', -451909262557.38745),
 ('Information_2015', -451909262557.38824),
 ('Finance and insurance, and real estate and rental and leasing_2015',
  -451909262557.3954),
 ('Professional, scientific, and management, and administrative and waste management services_2015',
  -451909262557.389),
 ('Educational services, and health care and social assistance_2015',
  -451909262557.3944),
 ('Arts, entertainment, and recreation, and accommodation and food services_2015',
  -451909262557.3855),
 ('Other services, except public administration_2015', -451909262557.3916),
 ('Public administration_2015', -451909262557.38513)]

In [14]:
#Prediction of test set
y_pred_mlr= mlr.predict(x_test)

from sklearn import metrics
meanAbErr = metrics.mean_absolute_error(y_test, y_pred_mlr)
meanSqErr = metrics.mean_squared_error(y_test, y_pred_mlr)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(y_test, y_pred_mlr))
print('R squared: {:.2f}'.format(mlr.score(x_test,y_test)))
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

R squared: -0.00
Mean Absolute Error: 0.2348090277777778
Mean Square Error: 0.2215855916341146
Root Mean Square Error: 0.4707287877686201

In [15]:
x = data_new[['Agriculture, forestry, fishing and hunting, and mining_2019','Construction_2019','Manufacturing_2019','Wholesale trade_2019','Retail trade_2019', 'Transportation and warehousing, and utilities_2019','Information_2019','Finance and insurance, and real estate and rental and leasing_2019', 'Professional, scientific, and management, and administrative and waste management services_2019','Educational services, and health care and social assistance_2019','Arts, entertainment, and recreation, and accommodation and food services_2019','Other services, except public administration_2019','Public administration_2019']]
y = data_new['2019_Binning']

from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data = pd.DataFrame()
vif_data["feature"] = x.columns
vif_data["VIF"] = [variance_inflation_factor(x.values, i) for i in range(len(x.columns))]
print(vif_data)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=100)

from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train, y_train)

                                              feature        VIF
0   Agriculture, forestry, fishing and hunting, an...   1.705317
1                                   Construction_2019  16.924155
2                                  Manufacturing_2019   5.763288
3                                Wholesale trade_2019  13.255246
4                                   Retail trade_2019  46.507569
5   Transportation and warehousing, and utilities_...   9.876562
6                                    Information_2019   9.108604
7   Finance and insurance, and real estate and ren...  12.724922
8   Professional, scientific, and management, and ...  19.441753
9   Educational services, and health care and soci...  23.960207
10  Arts, entertainment, and recreation, and accom...  15.605284
11  Other services, except public administration_2019  25.649430
12                         Public administration_2019   5.515734

LinearRegression()

In [16]:
print("Intercept: ", mlr.intercept_)
print("Coefficients:")
list(zip(x, mlr.coef_))

Intercept:  111519504530910.33
Coefficients:

[('Agriculture, forestry, fishing and hunting, and mining_2019',
  -1115195045309.0583),
 ('Construction_2019', -1115195045309.1008),
 ('Manufacturing_2019', -1115195045309.0889),
 ('Wholesale trade_2019', -1115195045309.053),
 ('Retail trade_2019', -1115195045309.092),
 ('Transportation and warehousing, and utilities_2019', -1115195045309.077),
 ('Information_2019', -1115195045309.1167),
 ('Finance and insurance, and real estate and rental and leasing_2019',
  -1115195045309.0928),
 ('Professional, scientific, and management, and administrative and waste management services_2019',
  -1115195045309.0671),
 ('Educational services, and health care and social assistance_2019',
  -1115195045309.0837),
 ('Arts, entertainment, and recreation, and accommodation and food services_2019',
  -1115195045309.089),
 ('Other services, except public administration_2019', -1115195045309.0474),
 ('Public administration_2019', -1115195045309.094)]

In [17]:
#Prediction of test set
y_pred_mlr= mlr.predict(x_test)

from sklearn import metrics
meanAbErr = metrics.mean_absolute_error(y_test, y_pred_mlr)
meanSqErr = metrics.mean_squared_error(y_test, y_pred_mlr)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(y_test, y_pred_mlr))
print('R squared: {:.2f}'.format(mlr.score(x_test,y_test)))
print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

R squared: 0.02
Mean Absolute Error: 0.22916666666666666
Mean Square Error: 0.180999755859375
Root Mean Square Error: 0.4254406607969847